version: 2

before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X github.com/Mario-F/cert-manager-selfservice/internal/config.Version=v{{.Version}}
  goos:
  - freebsd
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - '7'
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  use: git
  sort: asc
  filters:
    exclude:
    - '^chore:'
