before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X github.com/Mario-F/cert-manager-selfservice/internal/config.Version=v{{.Version}}
  goos:
  - freebsd
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - 7
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  use: git
  sort: asc
  filters:
    exclude:
    - '^chore:'
