# Docs: https://swagger.io/docs/specification/about/
---
openapi: 3.0.3
info:
  title: Cert Manager Selfservice API
  version: 1.0.0
servers:
  - url: http://localhost:8030/api/v1
paths:
  /status:
    get:
      summary: Returns status of the cert-manager-selfservice
      responses:
        '200':
          description: A json object represent the status
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      required:
                        - time
                        - message
                        - severity
                      properties:
                        time:
                          type: string
                          format: date-time
                        severity:
                          type: string
                          enum:
                          - "warning"
                          - "fatal"
                        message:
                          type: string
