# Docs: https://swagger.io/docs/specification/about/
---
openapi: 3.0.3
info:
  title: Cert Manager Selfservice API
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /status:
    get:
      summary: Returns status of the cert-manager-selfservice
      responses:
        '200':
          description: A json object represent the status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
components:
  schemas:
    Status:
      type: object
      properties:
        messages:
          description: This are event messages produced by the cert-manager-selfservice
          type: array
          items:
            $ref: '#/components/schemas/StatusMessage'
        certificates:
          $ref: '#/components/schemas/StatusCertificates'
      required:
        - messages
        - certificates
    StatusMessage:
      type: object
      required:
        - time
        - message
        - severity
      properties:
        time:
          type: string
          format: date-time
        severity:
          type: string
          enum:
            - info
            - warning
            - error
        message:
          type: string
    StatusCertificates:
      description: This is a overview of all certificates status
      type: object
      required:
        - total
        - pending
        - ready
        - failed
        - unknown
      properties:
        total:
          type: integer
        pending:
          type: integer
        ready:
          type: integer
        failed:
          type: integer
        unknown:
          type: integer

