---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-certificate
spec:
  commonName: test-certificate.example.com
  secretName: test-certificate
  dnsNames:
    - test-certificate.example.com
  issuerRef:
    kind: ClusterIssuer
    name: cms-development-cluster-issuer
