---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cms-development-cluster-issuer
spec:
  ca:
    secretName: cms-dev-key-pair
---
apiVersion: v1
kind: Secret
metadata:
  name: cms-dev-key-pair
data:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEBTCCAu2gAwIBAgIUdesofcA9o89A7W3hJ5i5WYP8O2owDQYJKoZIhvcNAQEL
    BQAwgZExCzAJBgNVBAYTAkRFMREwDwYDVQQIDAhJbnRlcm5ldDEPMA0GA1UEBwwG
    R2l0aHViMSEwHwYDVQQKDBhjZXJ0LW1hbmFnZXItc2VsZnNlcnZpY2UxFjAUBgNV
    BAMMDWZyaXRzY2hlbi5uZXQxIzAhBgkqhkiG9w0BCQEWFGdpdGh1YkBmcml0c2No
    ZW4ubmV0MB4XDTIyMDYxOTE1NDgzN1oXDTQyMDYxNDE1NDgzN1owgZExCzAJBgNV
    BAYTAkRFMREwDwYDVQQIDAhJbnRlcm5ldDEPMA0GA1UEBwwGR2l0aHViMSEwHwYD
    VQQKDBhjZXJ0LW1hbmFnZXItc2VsZnNlcnZpY2UxFjAUBgNVBAMMDWZyaXRzY2hl
    bi5uZXQxIzAhBgkqhkiG9w0BCQEWFGdpdGh1YkBmcml0c2NoZW4ubmV0MIIBIjAN
    BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8P469Xd/ZlVKF9B6i0rL6yynYvxW
    OkHv3oT/6r/qlkPJ9pDn+aDn1T7EnkyPZrd3HdXOtAWue4PcBd3HRkHZssdYoCHB
    r3JOvzlxmc4rQgF0zJbm2jByxbJJSTjcELLWt9oc/OKJC8/qDNpeMe525tgYc7Ho
    0uOYQ/tPq9OTgblCexSTYiReiW+7Ew4hzNLLtvuUKvnn/X0LPDSpe0tyn1vaXaaL
    SfYTNucBxY+R+4ql2VQUturdWhMW9A0LXBt7PCYkDxMq8g59lk0JWab9nl/0MGvk
    g3c3M+htvmPXh2p7sZKPCvoiFYsBQwBtnXSZk4IvrbxANCodJmXPzFZ/+QIDAQAB
    o1MwUTAdBgNVHQ4EFgQUjjZ/neFFyN9zay4vAymNhlmjDyswHwYDVR0jBBgwFoAU
    jjZ/neFFyN9zay4vAymNhlmjDyswDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0B
    AQsFAAOCAQEAfJ95ymYxyaKGBOpcKdqpQHKZlk/NBSy0HlV+gHzhjLij7v62y4QJ
    c0zFpTiXOtwZlvCJqpXEXhrxT+89n77GdzYoi7qibIXuYREVtQXYPcxhgueRAYRv
    cYM6SPVDGx7YGcyAyBCA/xzQ5pb1t+hwE+W0gi83FJM3BAet7cuxZ11vhAlsaC+g
    xTBDK3wkcMEtsOm5ZLw6hfgMPvSaYNU7FAJWy27+WzCFNQyFZT5rf85Tuz84QKYL
    4UFdCENioCCzt7aF4Y9tFmU5EMGDi6hZTsM+BKOfK94vFaKoAMuontsK1wU2zAhk
    eVQHh6qYZMt4DuieeXoTbBCA3o5JBZ0tfQ==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEA8P469Xd/ZlVKF9B6i0rL6yynYvxWOkHv3oT/6r/qlkPJ9pDn
    +aDn1T7EnkyPZrd3HdXOtAWue4PcBd3HRkHZssdYoCHBr3JOvzlxmc4rQgF0zJbm
    2jByxbJJSTjcELLWt9oc/OKJC8/qDNpeMe525tgYc7Ho0uOYQ/tPq9OTgblCexST
    YiReiW+7Ew4hzNLLtvuUKvnn/X0LPDSpe0tyn1vaXaaLSfYTNucBxY+R+4ql2VQU
    turdWhMW9A0LXBt7PCYkDxMq8g59lk0JWab9nl/0MGvkg3c3M+htvmPXh2p7sZKP
    CvoiFYsBQwBtnXSZk4IvrbxANCodJmXPzFZ/+QIDAQABAoIBAQCvqfEaGlfQJR1U
    DJA21neb3jnJCnxkDMonHjVZTTlW/OTLiMa/DE3Q/+bcKJxi2BrIsZ/xUy7jM7N+
    xzFJghiIm4x7dP+0vpKuCtZGsaSQgXU86EYwBx6yAoovCHZI6cNf0mpM32fcJ1rI
    saf1p4geLqhsNOOsTWAhNZ/WdOvRoumwKarJHhtn/2hvNr1unF8ZAogAmJcCAI4t
    yL0uB793Prc11yZnMTQBEmC56JMaK9mzmJ9w+Z95OZynBYQkewa7AEnsc1lXxEvL
    WJxvg656ht9ia8GsozqAY3vvCyuTy+GFeN41VgWOdffjHp4bFjpugwG5Wrwt1x2q
    R7kcYgy9AoGBAPwbWik541Ay6/HLiYQ3oKoECntct32zIY5i1PgK23tiY4IMV75E
    EW2T83NEsJFjk/+mgat82+uafslvIQCODizov5461C3A8BBILf246EIOXVhqoXkm
    HQELC+lxvK5TDd8iiGhSk2HfPEZkQCa6W5aqObn0Jia4HQJ7C4XKbyN/AoGBAPS2
    8T9JhdLvGYh0bLd9vw/BXrPRCZuNOQNOtRT/gnkGgFMbFEUIo5bDnKGKwxO4i7wH
    Pdn20IbdrKeAok7n4uZc7FL9mAc73Cqhs6z5Ffx+xip6ghQ/jrOEXVvtkcfuEm02
    ApounLMPDl+Begq9im4BQaRfSrENd/12EorDiTiHAoGBAMb7k8M8VIVFW+NB4i2A
    doganmdV++Hz1AV9TljkwO1279GCinK7aQITJ7EQQ0jNzs+WjXxcFXy1OWMmGmdE
    uD2MC0oJZtUiFpjTT7GWE4OnsNeLeh2UDop3PJSp1+HD3gwDRqUIoBk8yGdK0zN+
    HbIic2OpJ7+hzAvcMHEOIYBjAoGBAI5t6/vpzvn2L+Y73QrvJUUGRxhhkjX2/Dfw
    l3ShQk8ueYHlQObtIEmfkIp1ORVBVBMcI+O4w6W7X8IeHFnQnT921hV3hASx0nL9
    qpYCY8mR/8S5iPxAAc56O9xFaZPz/MWTqfATMSEGolb0BRQ7PVbJZGtHCzIBpNTg
    4+nf5P4BAoGAIoyLo0fR2L4QKddfTErM1V2CbAECgDzG+kikyAI4mUDFbDrX3zg3
    wmYf8pVu8LU9rENOquEYYukkRa0qrGD9L9xkSV/tu6Ivs8Y+/bPc5Vck818ND4JE
    fhvLXHgvjRk/GR4ipG1WHpGyU+hjGSMUWKJk7q3KAayGmCY9+iXsxyQ=
    -----END RSA PRIVATE KEY-----
