---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cms-development-cluster-issuer
spec:
  ca:
    secretName: cms-dev-key-pair
---
apiVersion: v1
kind: Secret
metadata:
  name: cms-dev-key-pair
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVCVENDQXUyZ0F3SUJBZ0lVZGVzb2ZjQTlv
    ODlBN1czaEo1aTVXWVA4TzJvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2daRXhDekFKQmdOVkJBWVRB
    a1JGTVJFd0R3WURWUVFJREFoSmJuUmxjbTVsZERFUE1BMEdBMVVFQnd3RwpSMmwwYUhWaU1TRXdI
    d1lEVlFRS0RCaGpaWEowTFcxaGJtRm5aWEl0YzJWc1puTmxjblpwWTJVeEZqQVVCZ05WCkJBTU1E
    V1p5YVhSelkyaGxiaTV1WlhReEl6QWhCZ2txaGtpRzl3MEJDUUVXRkdkcGRHaDFZa0JtY21sMGMy
    Tm8KWlc0dWJtVjBNQjRYRFRJeU1EWXhPVEUxTkRnek4xb1hEVFF5TURZeE5ERTFORGd6TjFvd2da
    RXhDekFKQmdOVgpCQVlUQWtSRk1SRXdEd1lEVlFRSURBaEpiblJsY201bGRERVBNQTBHQTFVRUJ3
    d0dSMmwwYUhWaU1TRXdId1lEClZRUUtEQmhqWlhKMExXMWhibUZuWlhJdGMyVnNabk5sY25acFky
    VXhGakFVQmdOVkJBTU1EV1p5YVhSelkyaGwKYmk1dVpYUXhJekFoQmdrcWhraUc5dzBCQ1FFV0ZH
    ZHBkR2gxWWtCbWNtbDBjMk5vWlc0dWJtVjBNSUlCSWpBTgpCZ2txaGtpRzl3MEJBUUVGQUFPQ0FR
    OEFNSUlCQ2dLQ0FRRUE4UDQ2OVhkL1psVktGOUI2aTByTDZ5eW5ZdnhXCk9rSHYzb1QvNnIvcWxr
    UEo5cERuK2FEbjFUN0Vua3lQWnJkM0hkWE90QVd1ZTRQY0JkM0hSa0hac3NkWW9DSEIKcjNKT3Z6
    bHhtYzRyUWdGMHpKYm0yakJ5eGJKSlNUamNFTExXdDlvYy9PS0pDOC9xRE5wZU1lNTI1dGdZYzdI
    bwowdU9ZUS90UHE5T1RnYmxDZXhTVFlpUmVpVys3RXc0aHpOTEx0dnVVS3Zubi9YMExQRFNwZTB0
    eW4xdmFYYWFMClNmWVROdWNCeFkrUis0cWwyVlFVdHVyZFdoTVc5QTBMWEJ0N1BDWWtEeE1xOGc1
    OWxrMEpXYWI5bmwvME1HdmsKZzNjM00raHR2bVBYaDJwN3NaS1BDdm9pRllzQlF3QnRuWFNaazRJ
    dnJieEFOQ29kSm1YUHpGWi8rUUlEQVFBQgpvMU13VVRBZEJnTlZIUTRFRmdRVWpqWi9uZUZGeU45
    emF5NHZBeW1OaGxtakR5c3dId1lEVlIwakJCZ3dGb0FVCmpqWi9uZUZGeU45emF5NHZBeW1OaGxt
    akR5c3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEIKQVFzRkFBT0NBUUVBZko5
    NXltWXh5YUtHQk9wY0tkcXBRSEtabGsvTkJTeTBIbFYrZ0h6aGpMaWo3djYyeTRRSgpjMHpGcFRp
    WE90d1psdkNKcXBYRVhocnhUKzg5bjc3R2R6WW9pN3FpYklYdVlSRVZ0UVhZUGN4aGd1ZVJBWVJ2
    CmNZTTZTUFZER3g3WUdjeUF5QkNBL3h6UTVwYjF0K2h3RStXMGdpODNGSk0zQkFldDdjdXhaMTF2
    aEFsc2FDK2cKeFRCREszd2tjTUV0c09tNVpMdzZoZmdNUHZTYVlOVTdGQUpXeTI3K1d6Q0ZOUXlG
    WlQ1cmY4NVR1ejg0UUtZTAo0VUZkQ0VOaW9DQ3p0N2FGNFk5dEZtVTVFTUdEaTZoWlRzTStCS09m
    Szk0dkZhS29BTXVvbnRzSzF3VTJ6QWhrCmVWUUhoNnFZWk10NER1aWVlWG9UYkJDQTNvNUpCWjB0
    ZlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBOFA0NjlYZC9a
    bFZLRjlCNmkwckw2eXluWXZ4V09rSHYzb1QvNnIvcWxrUEo5cERuCithRG4xVDdFbmt5UFpyZDNI
    ZFhPdEFXdWU0UGNCZDNIUmtIWnNzZFlvQ0hCcjNKT3Z6bHhtYzRyUWdGMHpKYm0KMmpCeXhiSkpT
    VGpjRUxMV3Q5b2MvT0tKQzgvcUROcGVNZTUyNXRnWWM3SG8wdU9ZUS90UHE5T1RnYmxDZXhTVApZ
    aVJlaVcrN0V3NGh6TkxMdHZ1VUt2bm4vWDBMUERTcGUwdHluMXZhWGFhTFNmWVROdWNCeFkrUis0
    cWwyVlFVCnR1cmRXaE1XOUEwTFhCdDdQQ1lrRHhNcThnNTlsazBKV2FiOW5sLzBNR3ZrZzNjM00r
    aHR2bVBYaDJwN3NaS1AKQ3ZvaUZZc0JRd0J0blhTWms0SXZyYnhBTkNvZEptWFB6RlovK1FJREFR
    QUJBb0lCQVFDdnFmRWFHbGZRSlIxVQpESkEyMW5lYjNqbkpDbnhrRE1vbkhqVlpUVGxXL09UTGlN
    YS9ERTNRLytiY0tKeGkyQnJJc1oveFV5N2pNN04rCnh6RkpnaGlJbTR4N2RQKzB2cEt1Q3RaR3Nh
    U1FnWFU4NkVZd0J4NnlBb292Q0haSTZjTmYwbXBNMzJmY0oxckkKc2FmMXA0Z2VMcWhzTk9Pc1RX
    QWhOWi9XZE92Um91bXdLYXJKSGh0bi8yaHZOcjF1bkY4WkFvZ0FtSmNDQUk0dAp5TDB1Qjc5M1By
    YzExeVpuTVRRQkVtQzU2Sk1hSzltem1KOXcrWjk1T1p5bkJZUWtld2E3QUVuc2MxbFh4RXZMCldK
    eHZnNjU2aHQ5aWE4R3NvenFBWTN2dkN5dVR5K0dGZU40MVZnV09kZmZqSHA0YkZqcHVnd0c1V3J3
    dDF4MnEKUjdrY1lneTlBb0dCQVB3YldpazU0MUF5Ni9ITGlZUTNvS29FQ250Y3QzMnpJWTVpMVBn
    SzIzdGlZNElNVjc1RQpFVzJUODNORXNKRmprLyttZ2F0ODIrdWFmc2x2SVFDT0Rpem92NTQ2MUMz
    QThCQklMZjI0NkVJT1hWaHFvWGttCkhRRUxDK2x4dks1VERkOGlpR2hTazJIZlBFWmtRQ2E2VzVh
    cU9ibjBKaWE0SFFKN0M0WEtieU4vQW9HQkFQUzIKOFQ5SmhkTHZHWWgwYkxkOXZ3L0JYclBSQ1p1
    Tk9RTk90UlQvZ25rR2dGTWJGRVVJbzViRG5LR0t3eE80aTd3SApQZG4yMEliZHJLZUFvazduNHVa
    YzdGTDltQWM3M0NxaHM2ejVGZngreGlwNmdoUS9qck9FWFZ2dGtjZnVFbTAyCkFwb3VuTE1QRGwr
    QmVncTlpbTRCUWFSZlNyRU5kLzEyRW9yRGlUaUhBb0dCQU1iN2s4TThWSVZGVytOQjRpMkEKZG9n
    YW5tZFYrK0h6MUFWOVRsamt3TzEyNzlHQ2luSzdhUUlUSjdFUVEwak56cytXalh4Y0ZYeTFPV01t
    R21kRQp1RDJNQzBvSlp0VWlGcGpUVDdHV0U0T25zTmVMZWgyVURvcDNQSlNwMStIRDNnd0RScVVJ
    b0JrOHlHZEswek4rCkhiSWljMk9wSjcraHpBdmNNSEVPSVlCakFvR0JBSTV0Ni92cHp2bjJMK1k3
    M1FydkpVVUdSeGhoa2pYMi9EZncKbDNTaFFrOHVlWUhsUU9idElFbWZrSXAxT1JWQlZCTWNJK080
    dzZXN1g4SWVIRm5RblQ5MjFoVjNoQVN4MG5MOQpxcFlDWThtUi84UzVpUHhBQWM1Nk85eEZhWlB6
    L01XVHFmQVRNU0VHb2xiMEJSUTdQVmJKWkd0SEN6SUJwTlRnCjQrbmY1UDRCQW9HQUlveUxvMGZS
    Mkw0UUtkZGZURXJNMVYyQ2JBRUNnRHpHK2tpa3lBSTRtVURGYkRyWDN6ZzMKd21ZZjhwVnU4TFU5
    ckVOT3F1RVlZdWtrUmEwcXJHRDlMOXhrU1YvdHU2SXZzOFkrL2JQYzVWY2s4MThORDRKRQpmaHZM
    WEhndmpSay9HUjRpcEcxV0hwR3lVK2hqR1NNVVdLSms3cTNLQWF5R21DWTkraVhzeHlRPQotLS0t
    LUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
