name: integration

on: push

jobs:
  integration:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        k3s:
          - 'v1.32.2-k3s1'
        cert-manager-chart:
          - 'v1.17.1'
    name: k3s ${{ matrix.k3s }}, cert-manager-chart ${{ matrix.cert-manager-chart }}
    env:
      DEBUG: true
      K3S_VERSION: ${{ matrix.k3s }}
      CERT_MANAGER_VERSION: ${{ matrix.cert-manager-chart }}
    defaults:
      run:
        shell: 'script -q -e -c "bash {0}"'
    steps:
      - uses: actions/checkout@v2

      - run: ./integration/cluster.sh start

      - run: "echo 'TODO: create integrations tests'"

      - run: ./integration/cluster.sh stop
