name: testing

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node:
          - '18'
          - '19'
        go:
          - '1.18'
    name: Go ${{ matrix.go }}, Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: cd web && yarn
      - run: cd web && yarn build
      - run: cd web && yarn lint
      - run: cd web && yarn test:unit
      - run: cd web && yarn test:e2e:ci

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: make test
